env:
  es6: true
  node: true
extends: '@ridedott/eslint-config'
overrides:
  - env:
      jest: true
    files:
      - src/**/*.spec.ts
    rules:
      '@typescript-eslint/no-magic-numbers': off
      '@typescript-eslint/no-explicit-any': off
      '@typescript-eslint/no-non-null-assertion': off
      max-lines-per-function: off
      max-lines: 0
      max-statements: 0
      no-magic-numbers: 0
      unicorn/no-unsafe-regex: off
      unicorn/prevent-abbreviations:
        - error
        - whitelist:
            params: true
parserOptions:
  ecmaVersion: 2020
  project: tsconfig.json
  sourceType: module
