env:
  es6: true
  node: true
extends: '@ridedott/eslint-config'
overrides:
  - env:
      jest: true
    files:
      - src/**/*.spec.ts
    rules:
      '@typescript-eslint/no-magic-numbers': off
      '@typescript-eslint/camelcase': off
      '@typescript-eslint/no-require-imports': off
      '@typescript-eslint/no-var-requires': off
      max-lines-per-function: off
      no-console: 0
      no-magic-numbers: 0
      capitalized-comments: 0
      multiline-comment-style: 0
parserOptions:
  ecmaVersion: 2020
  project: tsconfig.json
  sourceType: module
